@protocol = https
@baseUrl = {{protocol}}://localhost:3000

### Sandbox-API | Root
GET {{baseUrl}}/

### Sandbox-API | Health
GET {{baseUrl}}/health

### Sandbox-API | Runtime Info
GET {{baseUrl}}/info

### Sandbox-API | Runtime Modules
GET {{baseUrl}}/modules

### Sandbox API | HTTP Success Response
GET {{baseUrl}}/http/success

### Sandbox API | HTTP Error Response
GET {{baseUrl}}/http/error
